version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - tensorflow

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://backend:8000

  tensorflow:
    build: ./tensorflow
    volumes:
      - ./tensorflow:/app
    ports:
      - "8501:8501"
    


networks:
  default:
    driver: bridge
